### ISSUE TITLE
yafc_formal.h5 - how to create this file?

### ISSUE THREAD

**Issue by johndpope** [p-kar/text-style-transfer-gan#2]
python main.py
======================= Parameters =======================
==========================================================
batch_size                    : 128
dataFile                      : data/yafc_formal.h5
jsonFile                      : data/yafc_formal.json
pdataFile                     : data/yafc_informal.h5
pjsonFile                     : data/yafc_informal.json
shuffle                       : True
train_mode                    : pretrain_lm
embedding_size                : 300
hidden_size                   : 350
num_rnn_layers                : 1
use_lstm                      : True
use_attention                 : True
epochs                        : 1000
lr                            : 1e-05
weight_decay                  : 0.0001
dropout_p                     : 0.2
max_norm                      : 1
enable_scheduled_sampling     : False
scheduled_sampling_decay_type : linear
scheduled_sampling_decay_factor: 0.005
scheduled_sampling_min_eps    : 0.5
log_dir                       : ./logs
num_sample_sents              : 5
log_iter                      : 10
sent_sample_iter              : 50
save_path                     : ./models
model_name                    : model
pretrained_lm1_model_path     : ./models/yafc_formal_lm_best.net
pretrained_lm2_model_path     : ./models/yafc_informal_lm_best.net
pretrained_seq2seq_model_path : ./models/yafc_formal_informal.net
pretrained_glove_vector_path  : ./data/glove/glove.twitter.27B.200d.txt
use_glove_embeddings          : True
num_searches                  : 1
g_update_step_diff            : 25
d_update_step_diff            : 1
lr_ratio_D_by_G               : 1.0
discount_factor               : 0.99
lamda_rl                      : 1.0
lamda_rec_ii                  : 0.01
lamda_rec_ij                  : 0.001
lamda_cos_ij                  : 0.1
skip_weight_decay             : 0.995
freeze_embeddings             : True
clamp_lower                   : -0.01
clamp_upper                   : 0.01
d_pretrain_num_epochs         : 3
disc_recalibrate              : 100
g_update_step_diff_recalib    : 200

########################################################

Traceback (most recent call last):
  File "main.py", line 1466, in <module>
    main(opts)
  File "main.py", line 1385, in main
    pretrain_language_model(opts)
  File "main.py", line 122, in pretrain_language_model
    loader = DataLoader(opts)
  File "misc/DataLoader.py", line 11, in __init__
    self.h5_file = h5py.File(opts.dataFile, 'r')
  File "/Users/admin/miniconda3/envs/pytorch/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/admin/miniconda3/envs/pytorch/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'data/yafc_formal.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
(pytorch) ➜  text-style-transfer-gan git:(master) ✗

**Comment by johndpope** [comment]
is it possible you could upload to google drive? it would save me training time.

**Comment by johndpope** [comment]
I tried to run python preprocess scripts - this just creates empty files. 

I added this file

**download_glove.py**
```python 
import chakin
chakin.download(number=17, save_dir='./glove')
```


<img width="517" alt="screen shot 2018-07-10 at 10 54 48 pm" src="https://user-images.githubusercontent.com/289994/42548267-507a1e82-8494-11e8-8dc3-599d938c1fa6.png">

**Comment by johndpope** [comment]
I have this file /glove/glove.twitter.27B.25d.txt

```shell
python preprocess_yafc.py
Number of sentences: 0
ntrain	nval	ntest
0	0	0
Number of words in vocab of training set for S1: 0
Number of words in vocab for S1 0
Number of total words in S1 0
Loading GloVe vectors from ./glove/glove.twitter.27B.25d.txt...
done
[]
Writing: yafc_informal.train.txt
Writing: yafc_informal.valid.txt
Writing: yafc_informal.test.txt

Number of words in vocab for training set for S2: 0
Number of words in vocab for S2: 0
Number of total words in S2: 0
[]
Writing: yafc_formal.train.txt
Writing: yafc_formal.valid.txt
Writing: yafc_formal.test.txt
```

**Comment by johndpope** [comment]
digging around - I presume the data is form yahoo / need to be a student to get data. how did you prepare other h5 files?
https://webscope.sandbox.yahoo.com/catalog.php?datatype=l&guccounter=1

**Comment by johndpope** [comment]
found this 
https://github.com/Maluuba/gensen/blob/master/data/embedding/glove2h5.py

**Comment by johndpope** [comment]
how to create yafc_formal.json json file?

**Comment by johndpope** [comment]
maybe we can use a different dataset -  https://github.com/assaflehr/language-style-transfer/blob/master/quora-question-pairs-bdaleypallen-overfit-problems.ipynb

**Comment by p-kar** [comment]
I fixed the paths in the `preprocess/preprocess_shakespeare.py` and `preprocess/preprocess_bible.py` files. You should be able be to generate the train, validation and test splits now. After you generate these files you can run the `misc/PreprocessH5.py.py` file to generate the h5 and json files. That file contains a sample invocation.

Unfortunately, we can't share the YAFC corpus directly. It was created by the authors of [https://arxiv.org/pdf/1803.06535.pdf](https://arxiv.org/pdf/1803.06535.pdf) using the Yahoo Answers corpus: [L6 - Yahoo! Answers Comprehensive Questions and Answers version 1.0](https://webscope.sandbox.yahoo.com/catalog.php?datatype=l). You should contact them directly for requesting that dataset.

**Comment by johndpope** [comment]
great - looking good.
